### ISSUE TITLE
AnvilGui Error

### ISSUE THREAD

**Issue by LogGits** [DerFrZocker/Ore-Control#3] opened 2021-07-31 07:18 UTC
Error:
```
WARN16:32:19
[ore-control]: Task #8225 for ore-control v2021.06.29 generated an exception
Console16:32:19
java.lang.ExceptionInInitializerError: null
at de.derfrzocker.ore.control.utils.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
at de.derfrzocker.ore.control.gui.WorldGui.lambda$handleCreateTemplate$6(WorldGui.java:156) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[patched_1.17.1.jar:git-Paper-138]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-138]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-138]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-138]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-138]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-138]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-138]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
at de.derfrzocker.ore.control.utils.anvilgui.version.VersionMatcher.lambda$match$1(VersionMatcher.java:52) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at de.derfrzocker.ore.control.utils.anvilgui.version.VersionMatcher.match(VersionMatcher.java:52) ~[?:?]
at de.derfrzocker.ore.control.utils.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
... 10 more
```
paper 1.17.1 build 138
OreControl 2021.06.29

**Comment by DerFrZocker** [comment] 2021-07-31 10:52
Will be fixed in a newer version, you can temporarily use the command `/orecontrol create <name>`

**Comment by l3unnyAnoF4** [comment] 2021-08-16 21:07
same `[03:57:29 WARN]: [ore-control] Task #4968 for ore-control v2021.06.29 generated an exception
java.lang.ExceptionInInitializerError: null
        at de.derfrzocker.ore.control.utils.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[?:?]
        at de.derfrzocker.ore.control.gui.WorldGui.lambda$handleCreateTemplate$6(WorldGui.java:156) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[ssspigot215380127605476636389.jar:SSSpigot2-1.17.1-20210814-b7ca50c]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[ssspigot215380127605476636389.jar:SSSpigot2-1.17.1-20210814-b7ca50c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1609) ~[ssspigot215380127605476636389.jar:SSSpigot2-1.17.1-20210814-b7ca50c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:502) ~[ssspigot215380127605476636389.jar:SSSpigot2-1.17.1-20210814-b7ca50c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[ssspigot215380127605476636389.jar:SSSpigot2-1.17.1-20210814-b7ca50c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1289) ~[ssspigot215380127605476636389.jar:SSSpigot2-1.17.1-20210814-b7ca50c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[ssspigot215380127605476636389.jar:SSSpigot2-1.17.1-20210814-b7ca50c]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
        at de.derfrzocker.ore.control.utils.anvilgui.version.VersionMatcher.lambda$match$1(VersionMatcher.java:52) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at de.derfrzocker.ore.control.utils.anvilgui.version.VersionMatcher.match(VersionMatcher.java:52) ~[?:?]
        at de.derfrzocker.ore.control.utils.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[?:?]
        ... 10 more`

**Comment by DerFrZocker** [comment] 2022-12-15 06:18
With v2 1.17 is no longer supported.

**Closed by DerFrZocker** 2022-12-15 06:18 UTC
Labels: bug
